

* Change log

Every section in this part lists the change of the versions

** <2014-05-25 Sun>
If the netcdf model is a classic model we can also enable 
the compression.

** <2014-05-25 Sun>
For passing attributes to the def_var routine we need
to ensure that the dictionary gets deleted if the user 
adds the key 'ATT_DELETE'.
However, for cases where some nodes are not part of the 
file we still need to enforce this to handle memory leakage
correctly. This has been fixed.

** <2014-05-25 Sun>
If a user request to change the default parallel access
to variables we will return immediately if the file is not
a parallel file.

** <2014-05-25 Sun>
Added possibility to delete the dictionary after calling
the def_var routine. 
By adding the key 'ATT_DELETE' it will delete all entries.
In case one is worried about memory leakage this can be used.

It is necessary, calling def_var(...,atts=('hello'.kv.'a'))
will result in memory leakage.


* Feature requests

- [ ] Variable filling of specific values
      I.e. add arguments to ncdf_def_var, etc

- [ ] <<inq_fill>> Adding FILL to the inquiry routines
      ncdf_inq(ncdf,...)

- [ ] [[inq_fill]] Consider changing the routine name ncdf_fill
      to something more meaning full
      Should probably be deprecated when implementing
      the inquiry fill statement
